
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>


test:
  <<: *default
  database: engineerQA_test
  

development:
  <<: *default
  database: engineerQA_development



production:
  <<: *default
  database: engidoor_production
  username: root

